---
title: Packaging your Python code
hero_image: images/banner.png
description: Learn to package your code as a distribution that people can install
listed: true
ingredient: false
copyedit: true
version: 4
last_tested: 2018-06-08
steps:
- title: What you will make
- title: Build a demo package
- title: Test your code
- title: Package your code
  completion:
  - engaged
- title: Install your module
- title: Share with the world
  completion:
  - internal
