title: Packaging-your-code
hero_image: images/banner.png
description: Packaging-your-code description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 4, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: animals, art, humour, space, photography, outdoors, music, games
technologies: electronic-components, sense-hat, raspberry-pi, html-css-javascript, blender, scratch, python
site_areas: projects
hardware: electronic-components, sense-hat, raspberry-pi
software: html-css-javascript, blender, scratch, python
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Step title